---

- stat:
    path: "{{ item_vol.device }}"
  register: stat_vol

- name: LVOL Setup LV
  lvol:
    state: present
    vg: "{{ lvol_vg_name }}"
    lv: "{{ item_vol.name }}"
    size: "{{ item_vol.size }}"
    force: "{{ item_vol.force }}"
  when: not(stat_vol.exists)
