---
- name: LVOL Install deps
  package:
    name: lvm2
    state: present

- set_fact:
    lvol_vg_name: "{{ item.vg_name }}"
    lvol_vg_pv: "{{ item.vg_pv }}"
    lvol_lv_dev: "{{ item.lv_dev }}"
  with_items:
    - "{{ disk_lvol }}"

- name: LVOL Setup VG
  lvg:
    vg: "{{ lvol_vg_name }}"
    pvs: "{{ lvol_vg_pv }}"

- name: LVOL Setup LV
  lvol:
    state: present
    vg: "{{ lvol_vg_name }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    force: "{{ item.force }}"
  with_items:
    - "{{ lvol_lv_dev }}"

- set_fact:
    disk_devices: "{{ lvol_lv_dev }}"
